/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeviceManagementScriptRunSummaryFromDiscriminatorValue, type DeviceManagementScriptRunSummary } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the runSummary property of the microsoft.graph.deviceManagementScript entity.
 */
export interface RunSummaryRequestBuilder extends BaseRequestBuilder<RunSummaryRequestBuilder> {
    /**
     * Run summary for device management script.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of DeviceManagementScriptRunSummary
     */
     get(requestConfiguration?: RequestConfiguration<RunSummaryRequestBuilderGetQueryParameters> | undefined) : Promise<DeviceManagementScriptRunSummary | undefined>;
    /**
     * Run summary for device management script.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RunSummaryRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Run summary for device management script.
 */
export interface RunSummaryRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RunSummaryRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RunSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createDeviceManagementScriptRunSummaryFromDiscriminatorValue,
        queryParametersMapper: RunSummaryRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const RunSummaryRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/deviceManagementScripts/{deviceManagementScript%2Did}/runSummary{?%24expand,%24select}";
/* tslint:enable */
/* eslint-enable */
