/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createGovernanceRoleAssignmentCollectionResponseFromDiscriminatorValue, createGovernanceRoleAssignmentFromDiscriminatorValue, serializeGovernanceRoleAssignment, type GovernanceRoleAssignment, type GovernanceRoleAssignmentCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, CountRequestBuilderUriTemplate, type CountRequestBuilder } from './count/';
import { ExportRequestBuilderRequestsMetadata, ExportRequestBuilderUriTemplate, type ExportRequestBuilder } from './exportEscaped/';
import { GovernanceRoleAssignmentItemRequestBuilderNavigationMetadata, GovernanceRoleAssignmentItemRequestBuilderRequestsMetadata, GovernanceRoleAssignmentItemRequestBuilderUriTemplate, type GovernanceRoleAssignmentItemRequestBuilder } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the collection of governanceRoleAssignment entities.
 */
export interface GovernanceRoleAssignmentsRequestBuilder extends BaseRequestBuilder<GovernanceRoleAssignmentsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to call the export method.
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * Provides operations to manage the collection of governanceRoleAssignment entities.
     * @param governanceRoleAssignmentId The unique identifier of governanceRoleAssignment
     * @returns a GovernanceRoleAssignmentItemRequestBuilder
     */
     byGovernanceRoleAssignmentId(governanceRoleAssignmentId: string) : GovernanceRoleAssignmentItemRequestBuilder;
    /**
     * Get entities from governanceRoleAssignments
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of GovernanceRoleAssignmentCollectionResponse
     */
     get(requestConfiguration?: RequestConfiguration<GovernanceRoleAssignmentsRequestBuilderGetQueryParameters> | undefined) : Promise<GovernanceRoleAssignmentCollectionResponse | undefined>;
    /**
     * Add new entity to governanceRoleAssignments
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of GovernanceRoleAssignment
     */
     post(body: GovernanceRoleAssignment, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GovernanceRoleAssignment | undefined>;
    /**
     * Get entities from governanceRoleAssignments
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GovernanceRoleAssignmentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Add new entity to governanceRoleAssignments
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: GovernanceRoleAssignment, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get entities from governanceRoleAssignments
 */
export interface GovernanceRoleAssignmentsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const GovernanceRoleAssignmentsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GovernanceRoleAssignmentsRequestBuilderNavigationMetadata: Record<Exclude<keyof GovernanceRoleAssignmentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGovernanceRoleAssignmentId: {
        uriTemplate: GovernanceRoleAssignmentItemRequestBuilderUriTemplate,
        requestsMetadata: GovernanceRoleAssignmentItemRequestBuilderRequestsMetadata,
        navigationMetadata: GovernanceRoleAssignmentItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["governanceRoleAssignment%2Did"],
    },
    count: {
        uriTemplate: CountRequestBuilderUriTemplate,
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
    exportEscaped: {
        uriTemplate: ExportRequestBuilderUriTemplate,
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const GovernanceRoleAssignmentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createGovernanceRoleAssignmentCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: GovernanceRoleAssignmentsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createGovernanceRoleAssignmentFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeGovernanceRoleAssignment,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const GovernanceRoleAssignmentsRequestBuilderUriTemplate = "{+baseurl}/governanceRoleAssignments{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/* tslint:enable */
/* eslint-enable */
