# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# File initially created using https://github.com/MIchaelMainer/policyservicetoolkit/blob/main/branch_protection_export.ps1.

name: msgraph-beta-sdk-typescript-branch-protection
description: Branch protection policy for the msgraph-beta-sdk-typescript repository
resource: repository
configuration:
  branchProtectionRules:

