/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeviceManagementResourceAccessProfileBaseCollectionResponseFromDiscriminatorValue, createDeviceManagementResourceAccessProfileBaseFromDiscriminatorValue, serializeDeviceManagementResourceAccessProfileBase, type DeviceManagementResourceAccessProfileBase, type DeviceManagementResourceAccessProfileBaseCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/';
import { DeviceManagementResourceAccessProfileBaseItemRequestBuilderNavigationMetadata, DeviceManagementResourceAccessProfileBaseItemRequestBuilderRequestsMetadata, type DeviceManagementResourceAccessProfileBaseItemRequestBuilder } from './item/';
import { QueryByPlatformTypeRequestBuilderRequestsMetadata, type QueryByPlatformTypeRequestBuilder } from './queryByPlatformType/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetOrderbyQueryParameterType = (typeof GetOrderbyQueryParameterTypeObject)[keyof typeof GetOrderbyQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Provides operations to manage the resourceAccessProfiles property of the microsoft.graph.deviceManagement entity.
 */
export interface ResourceAccessProfilesRequestBuilder extends BaseRequestBuilder<ResourceAccessProfilesRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to call the queryByPlatformType method.
     */
    get queryByPlatformType(): QueryByPlatformTypeRequestBuilder;
    /**
     * Provides operations to manage the resourceAccessProfiles property of the microsoft.graph.deviceManagement entity.
     * @param deviceManagementResourceAccessProfileBaseId The unique identifier of deviceManagementResourceAccessProfileBase
     * @returns {DeviceManagementResourceAccessProfileBaseItemRequestBuilder}
     */
     byDeviceManagementResourceAccessProfileBaseId(deviceManagementResourceAccessProfileBaseId: string) : DeviceManagementResourceAccessProfileBaseItemRequestBuilder;
    /**
     * Collection of resource access settings associated with account.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeviceManagementResourceAccessProfileBaseCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<ResourceAccessProfilesRequestBuilderGetQueryParameters> | undefined) : Promise<DeviceManagementResourceAccessProfileBaseCollectionResponse | undefined>;
    /**
     * Create new navigation property to resourceAccessProfiles for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeviceManagementResourceAccessProfileBase>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: DeviceManagementResourceAccessProfileBase, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeviceManagementResourceAccessProfileBase | undefined>;
    /**
     * Collection of resource access settings associated with account.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ResourceAccessProfilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to resourceAccessProfiles for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DeviceManagementResourceAccessProfileBase, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Collection of resource access settings associated with account.
 */
export interface ResourceAccessProfilesRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: GetOrderbyQueryParameterType[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const ResourceAccessProfilesRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/resourceAccessProfiles{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Provides operations to manage the resourceAccessProfiles property of the microsoft.graph.deviceManagement entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
    Assignments: "assignments",
} as const;
/**
 * Provides operations to manage the resourceAccessProfiles property of the microsoft.graph.deviceManagement entity.
 */
export const GetOrderbyQueryParameterTypeObject = {
    Id: "id",
    IdDesc: "id desc",
    CreationDateTime: "creationDateTime",
    CreationDateTimeDesc: "creationDateTime desc",
    Description: "description",
    DescriptionDesc: "description desc",
    DisplayName: "displayName",
    DisplayNameDesc: "displayName desc",
    LastModifiedDateTime: "lastModifiedDateTime",
    LastModifiedDateTimeDesc: "lastModifiedDateTime desc",
    RoleScopeTagIds: "roleScopeTagIds",
    RoleScopeTagIdsDesc: "roleScopeTagIds desc",
    Version: "version",
    VersionDesc: "version desc",
} as const;
/**
 * Provides operations to manage the resourceAccessProfiles property of the microsoft.graph.deviceManagement entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    CreationDateTime: "creationDateTime",
    Description: "description",
    DisplayName: "displayName",
    LastModifiedDateTime: "lastModifiedDateTime",
    RoleScopeTagIds: "roleScopeTagIds",
    Version: "version",
    Assignments: "assignments",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ResourceAccessProfilesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourceAccessProfilesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourceAccessProfilesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDeviceManagementResourceAccessProfileBaseId: {
        requestsMetadata: DeviceManagementResourceAccessProfileBaseItemRequestBuilderRequestsMetadata,
        navigationMetadata: DeviceManagementResourceAccessProfileBaseItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["deviceManagementResourceAccessProfileBase%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
    queryByPlatformType: {
        requestsMetadata: QueryByPlatformTypeRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResourceAccessProfilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ResourceAccessProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeviceManagementResourceAccessProfileBaseCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: ResourceAccessProfilesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ResourceAccessProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeviceManagementResourceAccessProfileBaseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeviceManagementResourceAccessProfileBase,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
