/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createCountryRegionFromDiscriminatorValue, serializeCountryRegion, type CountryRegion } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the countriesRegions property of the microsoft.graph.company entity.
 */
export interface CountryRegionItemRequestBuilder extends BaseRequestBuilder<CountryRegionItemRequestBuilder> {
    /**
     * Delete navigation property countriesRegions for financials
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get countriesRegions from financials
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CountryRegion>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<CountryRegionItemRequestBuilderGetQueryParameters> | undefined) : Promise<CountryRegion | undefined>;
    /**
     * Update the navigation property countriesRegions in financials
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CountryRegion>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: CountryRegion, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CountryRegion | undefined>;
    /**
     * Delete navigation property countriesRegions for financials
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get countriesRegions from financials
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CountryRegionItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property countriesRegions in financials
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: CountryRegion, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get countriesRegions from financials
 */
export interface CountryRegionItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
}
export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const CountryRegionItemRequestBuilderUriTemplate = "{+baseurl}/financials/companies/{company%2Did}/countriesRegions/{countryRegion%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CountryRegionItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CountryRegionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: CountryRegionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: CountryRegionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCountryRegionFromDiscriminatorValue,
        queryParametersMapper: CountryRegionItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: CountryRegionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCountryRegionFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCountryRegion,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Provides operations to manage the countriesRegions property of the microsoft.graph.company entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
} as const;
/**
 * Provides operations to manage the countriesRegions property of the microsoft.graph.company entity.
 */
export const GetSelectQueryParameterTypeObject = {
    AddressFormat: "addressFormat",
    Code: "code",
    DisplayName: "displayName",
    Id: "id",
    LastModifiedDateTime: "lastModifiedDateTime",
} as const;
/* tslint:enable */
/* eslint-enable */
