/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createNetworkAccessRootFromDiscriminatorValue, serializeNetworkAccessRoot, type NetworkAccessRoot } from '@microsoft/msgraph-beta-sdk/models/networkaccess/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { ConnectivityRequestBuilderNavigationMetadata, ConnectivityRequestBuilderRequestsMetadata, ConnectivityRequestBuilderUriTemplate, type ConnectivityRequestBuilder } from './connectivity/';
import { FilteringPoliciesRequestBuilderNavigationMetadata, FilteringPoliciesRequestBuilderRequestsMetadata, FilteringPoliciesRequestBuilderUriTemplate, type FilteringPoliciesRequestBuilder } from './filteringPolicies/';
import { FilteringProfilesRequestBuilderNavigationMetadata, FilteringProfilesRequestBuilderRequestsMetadata, FilteringProfilesRequestBuilderUriTemplate, type FilteringProfilesRequestBuilder } from './filteringProfiles/';
import { ForwardingPoliciesRequestBuilderNavigationMetadata, ForwardingPoliciesRequestBuilderRequestsMetadata, ForwardingPoliciesRequestBuilderUriTemplate, type ForwardingPoliciesRequestBuilder } from './forwardingPolicies/';
import { ForwardingProfilesRequestBuilderNavigationMetadata, ForwardingProfilesRequestBuilderRequestsMetadata, ForwardingProfilesRequestBuilderUriTemplate, type ForwardingProfilesRequestBuilder } from './forwardingProfiles/';
import { LogsRequestBuilderNavigationMetadata, LogsRequestBuilderRequestsMetadata, LogsRequestBuilderUriTemplate, type LogsRequestBuilder } from './logs/';
import { MicrosoftGraphNetworkaccessOnboardRequestBuilderRequestsMetadata, MicrosoftGraphNetworkaccessOnboardRequestBuilderUriTemplate, type MicrosoftGraphNetworkaccessOnboardRequestBuilder } from './microsoftGraphNetworkaccessOnboard/';
import { ReportsRequestBuilderNavigationMetadata, ReportsRequestBuilderRequestsMetadata, ReportsRequestBuilderUriTemplate, type ReportsRequestBuilder } from './reports/';
import { SettingsRequestBuilderNavigationMetadata, SettingsRequestBuilderRequestsMetadata, SettingsRequestBuilderUriTemplate, type SettingsRequestBuilder } from './settings/';
import { TenantStatusRequestBuilderRequestsMetadata, TenantStatusRequestBuilderUriTemplate, type TenantStatusRequestBuilder } from './tenantStatus/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the networkAccessRoot singleton.
 */
export interface NetworkAccessRequestBuilder extends BaseRequestBuilder<NetworkAccessRequestBuilder> {
    /**
     * Provides operations to manage the connectivity property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get connectivity(): ConnectivityRequestBuilder;
    /**
     * Provides operations to manage the filteringPolicies property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get filteringPolicies(): FilteringPoliciesRequestBuilder;
    /**
     * Provides operations to manage the filteringProfiles property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get filteringProfiles(): FilteringProfilesRequestBuilder;
    /**
     * Provides operations to manage the forwardingPolicies property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get forwardingPolicies(): ForwardingPoliciesRequestBuilder;
    /**
     * Provides operations to manage the forwardingProfiles property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get forwardingProfiles(): ForwardingProfilesRequestBuilder;
    /**
     * Provides operations to manage the logs property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get logs(): LogsRequestBuilder;
    /**
     * Provides operations to call the onboard method.
     */
    get microsoftGraphNetworkaccessOnboard(): MicrosoftGraphNetworkaccessOnboardRequestBuilder;
    /**
     * Provides operations to manage the reports property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get reports(): ReportsRequestBuilder;
    /**
     * Provides operations to manage the settings property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get settings(): SettingsRequestBuilder;
    /**
     * Provides operations to manage the tenantStatus property of the microsoft.graph.networkaccess.networkAccessRoot entity.
     */
    get tenantStatus(): TenantStatusRequestBuilder;
    /**
     * Get networkAccess
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of NetworkAccessRoot
     */
     get(requestConfiguration?: RequestConfiguration<NetworkAccessRequestBuilderGetQueryParameters> | undefined) : Promise<NetworkAccessRoot | undefined>;
    /**
     * Update networkAccess
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of NetworkAccessRoot
     */
     patch(body: NetworkAccessRoot, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NetworkAccessRoot | undefined>;
    /**
     * Get networkAccess
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<NetworkAccessRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update networkAccess
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPatchRequestInformation(body: NetworkAccessRoot, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get networkAccess
 */
export interface NetworkAccessRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const NetworkAccessRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NetworkAccessRequestBuilderNavigationMetadata: Record<Exclude<keyof NetworkAccessRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    connectivity: {
        uriTemplate: ConnectivityRequestBuilderUriTemplate,
        requestsMetadata: ConnectivityRequestBuilderRequestsMetadata,
        navigationMetadata: ConnectivityRequestBuilderNavigationMetadata,
    },
    filteringPolicies: {
        uriTemplate: FilteringPoliciesRequestBuilderUriTemplate,
        requestsMetadata: FilteringPoliciesRequestBuilderRequestsMetadata,
        navigationMetadata: FilteringPoliciesRequestBuilderNavigationMetadata,
    },
    filteringProfiles: {
        uriTemplate: FilteringProfilesRequestBuilderUriTemplate,
        requestsMetadata: FilteringProfilesRequestBuilderRequestsMetadata,
        navigationMetadata: FilteringProfilesRequestBuilderNavigationMetadata,
    },
    forwardingPolicies: {
        uriTemplate: ForwardingPoliciesRequestBuilderUriTemplate,
        requestsMetadata: ForwardingPoliciesRequestBuilderRequestsMetadata,
        navigationMetadata: ForwardingPoliciesRequestBuilderNavigationMetadata,
    },
    forwardingProfiles: {
        uriTemplate: ForwardingProfilesRequestBuilderUriTemplate,
        requestsMetadata: ForwardingProfilesRequestBuilderRequestsMetadata,
        navigationMetadata: ForwardingProfilesRequestBuilderNavigationMetadata,
    },
    logs: {
        uriTemplate: LogsRequestBuilderUriTemplate,
        requestsMetadata: LogsRequestBuilderRequestsMetadata,
        navigationMetadata: LogsRequestBuilderNavigationMetadata,
    },
    microsoftGraphNetworkaccessOnboard: {
        uriTemplate: MicrosoftGraphNetworkaccessOnboardRequestBuilderUriTemplate,
        requestsMetadata: MicrosoftGraphNetworkaccessOnboardRequestBuilderRequestsMetadata,
    },
    reports: {
        uriTemplate: ReportsRequestBuilderUriTemplate,
        requestsMetadata: ReportsRequestBuilderRequestsMetadata,
        navigationMetadata: ReportsRequestBuilderNavigationMetadata,
    },
    settings: {
        uriTemplate: SettingsRequestBuilderUriTemplate,
        requestsMetadata: SettingsRequestBuilderRequestsMetadata,
        navigationMetadata: SettingsRequestBuilderNavigationMetadata,
    },
    tenantStatus: {
        uriTemplate: TenantStatusRequestBuilderUriTemplate,
        requestsMetadata: TenantStatusRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const NetworkAccessRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createNetworkAccessRootFromDiscriminatorValue,
        queryParametersMapper: NetworkAccessRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createNetworkAccessRootFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNetworkAccessRoot,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const NetworkAccessRequestBuilderUriTemplate = "{+baseurl}/networkAccess{?%24select,%24expand}";
/* tslint:enable */
/* eslint-enable */
