/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeviceComplianceScriptRunSummaryFromDiscriminatorValue, serializeDeviceComplianceScriptRunSummary, type DeviceComplianceScriptRunSummary } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Provides operations to manage the runSummary property of the microsoft.graph.deviceComplianceScript entity.
 */
export interface RunSummaryRequestBuilder extends BaseRequestBuilder<RunSummaryRequestBuilder> {
    /**
     * Delete navigation property runSummary for deviceManagement
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * High level run summary for device compliance script.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeviceComplianceScriptRunSummary>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<RunSummaryRequestBuilderGetQueryParameters> | undefined) : Promise<DeviceComplianceScriptRunSummary | undefined>;
    /**
     * Update the navigation property runSummary in deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeviceComplianceScriptRunSummary>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: DeviceComplianceScriptRunSummary, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeviceComplianceScriptRunSummary | undefined>;
    /**
     * Delete navigation property runSummary for deviceManagement
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * High level run summary for device compliance script.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RunSummaryRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property runSummary in deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: DeviceComplianceScriptRunSummary, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * High level run summary for device compliance script.
 */
export interface RunSummaryRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
}
/**
 * Uri template for the request builder.
 */
export const RunSummaryRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/deviceComplianceScripts/{deviceComplianceScript%2Did}/runSummary{?%24expand,%24select}";
/**
 * Provides operations to manage the runSummary property of the microsoft.graph.deviceComplianceScript entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
} as const;
/**
 * Provides operations to manage the runSummary property of the microsoft.graph.deviceComplianceScript entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    DetectionScriptErrorDeviceCount: "detectionScriptErrorDeviceCount",
    DetectionScriptPendingDeviceCount: "detectionScriptPendingDeviceCount",
    IssueDetectedDeviceCount: "issueDetectedDeviceCount",
    LastScriptRunDateTime: "lastScriptRunDateTime",
    NoIssueDetectedDeviceCount: "noIssueDetectedDeviceCount",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RunSummaryRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RunSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RunSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: RunSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeviceComplianceScriptRunSummaryFromDiscriminatorValue,
        queryParametersMapper: RunSummaryRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: RunSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeviceComplianceScriptRunSummaryFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeviceComplianceScriptRunSummary,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
