/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a getGroupPolicySettingsDeviceSettingsReportPostRequestBody
 */
export function createGetGroupPolicySettingsDeviceSettingsReportPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetGroupPolicySettingsDeviceSettingsReportPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoGetGroupPolicySettingsDeviceSettingsReportPostRequestBody(getGroupPolicySettingsDeviceSettingsReportPostRequestBody: Partial<GetGroupPolicySettingsDeviceSettingsReportPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.backingStoreEnabled = true; },
        "filter": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.filter = n.getStringValue(); },
        "groupBy": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.groupBy = n.getCollectionOfPrimitiveValues<string>(); },
        "name": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.name = n.getStringValue(); },
        "orderBy": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.orderBy = n.getCollectionOfPrimitiveValues<string>(); },
        "search": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.search = n.getStringValue(); },
        "select": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.select = n.getCollectionOfPrimitiveValues<string>(); },
        "sessionId": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.sessionId = n.getStringValue(); },
        "skip": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.skip = n.getNumberValue(); },
        "top": n => { getGroupPolicySettingsDeviceSettingsReportPostRequestBody.top = n.getNumberValue(); },
    }
}
export interface GetGroupPolicySettingsDeviceSettingsReportPostRequestBody extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean;
    /**
     * The filter property
     */
    filter?: string;
    /**
     * The groupBy property
     */
    groupBy?: string[];
    /**
     * The name property
     */
    name?: string;
    /**
     * The orderBy property
     */
    orderBy?: string[];
    /**
     * The search property
     */
    search?: string;
    /**
     * The select property
     */
    select?: string[];
    /**
     * The sessionId property
     */
    sessionId?: string;
    /**
     * The skip property
     */
    skip?: number;
    /**
     * The top property
     */
    top?: number;
}
/**
 * Provides operations to call the getGroupPolicySettingsDeviceSettingsReport method.
 */
export interface GetGroupPolicySettingsDeviceSettingsReportRequestBuilder extends BaseRequestBuilder<GetGroupPolicySettingsDeviceSettingsReportRequestBuilder> {
    /**
     * Invoke action getGroupPolicySettingsDeviceSettingsReport
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     post(body: GetGroupPolicySettingsDeviceSettingsReportPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Invoke action getGroupPolicySettingsDeviceSettingsReport
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: GetGroupPolicySettingsDeviceSettingsReportPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeGetGroupPolicySettingsDeviceSettingsReportPostRequestBody(writer: SerializationWriter, getGroupPolicySettingsDeviceSettingsReportPostRequestBody: Partial<GetGroupPolicySettingsDeviceSettingsReportPostRequestBody> | undefined = {}) : void {
    writer.writeStringValue("filter", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.filter);
    writer.writeCollectionOfPrimitiveValues<string>("groupBy", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.groupBy);
    writer.writeStringValue("name", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.name);
    writer.writeCollectionOfPrimitiveValues<string>("orderBy", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.orderBy);
    writer.writeStringValue("search", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.search);
    writer.writeCollectionOfPrimitiveValues<string>("select", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.select);
    writer.writeStringValue("sessionId", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.sessionId);
    writer.writeNumberValue("skip", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.skip);
    writer.writeNumberValue("top", getGroupPolicySettingsDeviceSettingsReportPostRequestBody.top);
    writer.writeAdditionalData(getGroupPolicySettingsDeviceSettingsReportPostRequestBody.additionalData);
}
/**
 * Metadata for all the requests in the request builder.
 */
export const GetGroupPolicySettingsDeviceSettingsReportRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        responseBodyContentType: "application/octet-stream, application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeGetGroupPolicySettingsDeviceSettingsReportPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const GetGroupPolicySettingsDeviceSettingsReportRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/reports/getGroupPolicySettingsDeviceSettingsReport";
/* tslint:enable */
/* eslint-enable */
