/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCloudPcReviewStatusFromDiscriminatorValue, type CloudPcReviewStatus } from '@microsoft/msgraph-beta-sdk/models/';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to call the retrieveReviewStatus method.
 */
export interface RetrieveReviewStatusRequestBuilder extends BaseRequestBuilder<RetrieveReviewStatusRequestBuilder> {
    /**
     * Invoke function retrieveReviewStatus
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CloudPcReviewStatus>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CloudPcReviewStatus | undefined>;
    /**
     * Invoke function retrieveReviewStatus
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RetrieveReviewStatusRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/virtualEndpoint/cloudPCs/{cloudPC%2Did}/retrieveReviewStatus()";
/**
 * Metadata for all the requests in the request builder.
 */
export const RetrieveReviewStatusRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RetrieveReviewStatusRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCloudPcReviewStatusFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
