/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createServicePrincipalCreationConditionSetCollectionResponseFromDiscriminatorValue, createServicePrincipalCreationConditionSetFromDiscriminatorValue, serializeServicePrincipalCreationConditionSet, type ServicePrincipalCreationConditionSet, type ServicePrincipalCreationConditionSetCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, CountRequestBuilderUriTemplate, type CountRequestBuilder } from './count/';
import { ServicePrincipalCreationConditionSetItemRequestBuilderRequestsMetadata, ServicePrincipalCreationConditionSetItemRequestBuilderUriTemplate, type ServicePrincipalCreationConditionSetItemRequestBuilder } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the excludes property of the microsoft.graph.servicePrincipalCreationPolicy entity.
 */
export interface ExcludesRequestBuilder extends BaseRequestBuilder<ExcludesRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the excludes property of the microsoft.graph.servicePrincipalCreationPolicy entity.
     * @param servicePrincipalCreationConditionSetId The unique identifier of servicePrincipalCreationConditionSet
     * @returns a ServicePrincipalCreationConditionSetItemRequestBuilder
     */
     byServicePrincipalCreationConditionSetId(servicePrincipalCreationConditionSetId: string) : ServicePrincipalCreationConditionSetItemRequestBuilder;
    /**
     * Get excludes from policies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ServicePrincipalCreationConditionSetCollectionResponse
     */
     get(requestConfiguration?: RequestConfiguration<ExcludesRequestBuilderGetQueryParameters> | undefined) : Promise<ServicePrincipalCreationConditionSetCollectionResponse | undefined>;
    /**
     * Create new navigation property to excludes for policies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ServicePrincipalCreationConditionSet
     */
     post(body: ServicePrincipalCreationConditionSet, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServicePrincipalCreationConditionSet | undefined>;
    /**
     * Get excludes from policies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ExcludesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to excludes for policies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: ServicePrincipalCreationConditionSet, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get excludes from policies
 */
export interface ExcludesRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ExcludesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExcludesRequestBuilderNavigationMetadata: Record<Exclude<keyof ExcludesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byServicePrincipalCreationConditionSetId: {
        uriTemplate: ServicePrincipalCreationConditionSetItemRequestBuilderUriTemplate,
        requestsMetadata: ServicePrincipalCreationConditionSetItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["servicePrincipalCreationConditionSet%2Did"],
    },
    count: {
        uriTemplate: CountRequestBuilderUriTemplate,
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ExcludesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createServicePrincipalCreationConditionSetCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: ExcludesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createServicePrincipalCreationConditionSetFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServicePrincipalCreationConditionSet,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const ExcludesRequestBuilderUriTemplate = "{+baseurl}/policies/servicePrincipalCreationPolicies/{servicePrincipalCreationPolicy%2Did}/excludes{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/* tslint:enable */
/* eslint-enable */
