/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createManagementTemplateStepDeploymentFromDiscriminatorValue, serializeManagementTemplateStepDeployment, type ManagementTemplateStepDeployment } from '@microsoft/msgraph-beta-sdk/models/managedTenants/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChangeDeploymentStatusPostRequestBody extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean;
    /**
     * The managementTemplateStepId property
     */
    managementTemplateStepId?: string;
    /**
     * The status property
     */
    status?: string;
    /**
     * The tenantId property
     */
    tenantId?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangeDeploymentStatusPostRequestBody}
 */
export function createChangeDeploymentStatusPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangeDeploymentStatusPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoChangeDeploymentStatusPostRequestBody(changeDeploymentStatusPostRequestBody: Partial<ChangeDeploymentStatusPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { changeDeploymentStatusPostRequestBody.backingStoreEnabled = true; },
        "managementTemplateStepId": n => { changeDeploymentStatusPostRequestBody.managementTemplateStepId = n.getStringValue(); },
        "status": n => { changeDeploymentStatusPostRequestBody.status = n.getStringValue(); },
        "tenantId": n => { changeDeploymentStatusPostRequestBody.tenantId = n.getStringValue(); },
    }
}
/**
 * Provides operations to call the changeDeploymentStatus method.
 */
export interface MicrosoftGraphManagedTenantsChangeDeploymentStatusRequestBuilder extends BaseRequestBuilder<MicrosoftGraphManagedTenantsChangeDeploymentStatusRequestBuilder> {
    /**
     * Invoke action changeDeploymentStatus
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ManagementTemplateStepDeployment>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: ChangeDeploymentStatusPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ManagementTemplateStepDeployment | undefined>;
    /**
     * Invoke action changeDeploymentStatus
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ChangeDeploymentStatusPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeChangeDeploymentStatusPostRequestBody(writer: SerializationWriter, changeDeploymentStatusPostRequestBody: Partial<ChangeDeploymentStatusPostRequestBody> | undefined = {}) : void {
    writer.writeStringValue("managementTemplateStepId", changeDeploymentStatusPostRequestBody.managementTemplateStepId);
    writer.writeStringValue("status", changeDeploymentStatusPostRequestBody.status);
    writer.writeStringValue("tenantId", changeDeploymentStatusPostRequestBody.tenantId);
    writer.writeAdditionalData(changeDeploymentStatusPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const MicrosoftGraphManagedTenantsChangeDeploymentStatusRequestBuilderUriTemplate = "{+baseurl}/tenantRelationships/managedTenants/managementTemplateStepVersions/{managementTemplateStepVersion%2Did}/deployments/{managementTemplateStepDeployment%2Did}/microsoft.graph.managedTenants.changeDeploymentStatus";
/**
 * Metadata for all the requests in the request builder.
 */
export const MicrosoftGraphManagedTenantsChangeDeploymentStatusRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MicrosoftGraphManagedTenantsChangeDeploymentStatusRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createManagementTemplateStepDeploymentFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChangeDeploymentStatusPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
