/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccessReviewInstanceFromDiscriminatorValue, serializeAccessReviewInstance, type AccessReviewInstance } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { AcceptRecommendationsRequestBuilderRequestsMetadata, type AcceptRecommendationsRequestBuilder } from './acceptRecommendations/index.js';
// @ts-ignore
import { ApplyDecisionsRequestBuilderRequestsMetadata, type ApplyDecisionsRequestBuilder } from './applyDecisions/index.js';
// @ts-ignore
import { BatchApplyCustomDataProvidedResourceDecisionsRequestBuilderRequestsMetadata, type BatchApplyCustomDataProvidedResourceDecisionsRequestBuilder } from './batchApplyCustomDataProvidedResourceDecisions/index.js';
// @ts-ignore
import { BatchRecordDecisionsRequestBuilderRequestsMetadata, type BatchRecordDecisionsRequestBuilder } from './batchRecordDecisions/index.js';
// @ts-ignore
import { ContactedReviewersRequestBuilderNavigationMetadata, ContactedReviewersRequestBuilderRequestsMetadata, type ContactedReviewersRequestBuilder } from './contactedReviewers/index.js';
// @ts-ignore
import { DecisionsRequestBuilderNavigationMetadata, DecisionsRequestBuilderRequestsMetadata, type DecisionsRequestBuilder } from './decisions/index.js';
// @ts-ignore
import { DefinitionRequestBuilderRequestsMetadata, type DefinitionRequestBuilder } from './definition/index.js';
// @ts-ignore
import { ResetDecisionsRequestBuilderRequestsMetadata, type ResetDecisionsRequestBuilder } from './resetDecisions/index.js';
// @ts-ignore
import { SendReminderRequestBuilderRequestsMetadata, type SendReminderRequestBuilder } from './sendReminder/index.js';
// @ts-ignore
import { StagesRequestBuilderNavigationMetadata, StagesRequestBuilderRequestsMetadata, type StagesRequestBuilder } from './stages/index.js';
// @ts-ignore
import { StopRequestBuilderRequestsMetadata, type StopRequestBuilder } from './stop/index.js';
// @ts-ignore
import { StopApplyDecisionsRequestBuilderRequestsMetadata, type StopApplyDecisionsRequestBuilder } from './stopApplyDecisions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the instances property of the microsoft.graph.accessReviewScheduleDefinition entity.
 */
export interface AccessReviewInstanceItemRequestBuilder extends BaseRequestBuilder<AccessReviewInstanceItemRequestBuilder> {
    /**
     * Provides operations to call the acceptRecommendations method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get acceptRecommendations(): AcceptRecommendationsRequestBuilder;
    /**
     * Provides operations to call the applyDecisions method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get applyDecisions(): ApplyDecisionsRequestBuilder;
    /**
     * Provides operations to call the batchApplyCustomDataProvidedResourceDecisions method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get batchApplyCustomDataProvidedResourceDecisions(): BatchApplyCustomDataProvidedResourceDecisionsRequestBuilder;
    /**
     * Provides operations to call the batchRecordDecisions method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get batchRecordDecisions(): BatchRecordDecisionsRequestBuilder;
    /**
     * Provides operations to manage the contactedReviewers property of the microsoft.graph.accessReviewInstance entity.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get contactedReviewers(): ContactedReviewersRequestBuilder;
    /**
     * Provides operations to manage the decisions property of the microsoft.graph.accessReviewInstance entity.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get decisions(): DecisionsRequestBuilder;
    /**
     * Provides operations to manage the definition property of the microsoft.graph.accessReviewInstance entity.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get definition(): DefinitionRequestBuilder;
    /**
     * Provides operations to call the resetDecisions method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get resetDecisions(): ResetDecisionsRequestBuilder;
    /**
     * Provides operations to call the sendReminder method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get sendReminder(): SendReminderRequestBuilder;
    /**
     * Provides operations to manage the stages property of the microsoft.graph.accessReviewInstance entity.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get stages(): StagesRequestBuilder;
    /**
     * Provides operations to call the stop method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get stop(): StopRequestBuilder;
    /**
     * Provides operations to call the stopApplyDecisions method.
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
    get stopApplyDecisions(): StopApplyDecisionsRequestBuilder;
    /**
     * Delete navigation property instances for identityGovernance
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Retrieve an accessReviewInstance object using the identifier of an accessReviewInstance and its parent accessReviewScheduleDefinition. This returns all properties of the instance except for the associated accessReviewInstanceDecisionItems. To retrieve the decisions on the instance, use List accessReviewInstanceDecisionItem.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccessReviewInstance>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     * @see {@link https://learn.microsoft.com/graph/api/accessreviewinstance-get?view=graph-rest-beta|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<AccessReviewInstanceItemRequestBuilderGetQueryParameters> | undefined) : Promise<AccessReviewInstance | undefined>;
    /**
     * Update the properties of an accessReviewInstance object. Only the reviewers and fallbackReviewers properties can be updated but the scope property is also required in the request body. You can only add reviewers to the fallbackReviewers property but can't remove existing fallbackReviewers. To update an accessReviewInstance, its status must be InProgress.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccessReviewInstance>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     * @see {@link https://learn.microsoft.com/graph/api/accessreviewinstance-update?view=graph-rest-beta|Find more info here}
     */
     patch(body: AccessReviewInstance, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AccessReviewInstance | undefined>;
    /**
     * Delete navigation property instances for identityGovernance
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Retrieve an accessReviewInstance object using the identifier of an accessReviewInstance and its parent accessReviewScheduleDefinition. This returns all properties of the instance except for the associated accessReviewInstanceDecisionItems. To retrieve the decisions on the instance, use List accessReviewInstanceDecisionItem.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AccessReviewInstanceItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the properties of an accessReviewInstance object. Only the reviewers and fallbackReviewers properties can be updated but the scope property is also required in the request body. You can only add reviewers to the fallbackReviewers property but can't remove existing fallbackReviewers. To update an accessReviewInstance, its status must be InProgress.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2022-02/PrivatePreview:groupPeerOutlierInsights on 2021-10-21 and will be removed 2022-02-18
     */
     toPatchRequestInformation(body: AccessReviewInstance, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Retrieve an accessReviewInstance object using the identifier of an accessReviewInstance and its parent accessReviewScheduleDefinition. This returns all properties of the instance except for the associated accessReviewInstanceDecisionItems. To retrieve the decisions on the instance, use List accessReviewInstanceDecisionItem.
 */
export interface AccessReviewInstanceItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const AccessReviewInstanceItemRequestBuilderUriTemplate = "{+baseurl}/identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinition%2Did}/instances/{accessReviewInstance%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AccessReviewInstanceItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccessReviewInstanceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof AccessReviewInstanceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    acceptRecommendations: {
        requestsMetadata: AcceptRecommendationsRequestBuilderRequestsMetadata,
    },
    applyDecisions: {
        requestsMetadata: ApplyDecisionsRequestBuilderRequestsMetadata,
    },
    batchApplyCustomDataProvidedResourceDecisions: {
        requestsMetadata: BatchApplyCustomDataProvidedResourceDecisionsRequestBuilderRequestsMetadata,
    },
    batchRecordDecisions: {
        requestsMetadata: BatchRecordDecisionsRequestBuilderRequestsMetadata,
    },
    contactedReviewers: {
        requestsMetadata: ContactedReviewersRequestBuilderRequestsMetadata,
        navigationMetadata: ContactedReviewersRequestBuilderNavigationMetadata,
    },
    decisions: {
        requestsMetadata: DecisionsRequestBuilderRequestsMetadata,
        navigationMetadata: DecisionsRequestBuilderNavigationMetadata,
    },
    definition: {
        requestsMetadata: DefinitionRequestBuilderRequestsMetadata,
    },
    resetDecisions: {
        requestsMetadata: ResetDecisionsRequestBuilderRequestsMetadata,
    },
    sendReminder: {
        requestsMetadata: SendReminderRequestBuilderRequestsMetadata,
    },
    stages: {
        requestsMetadata: StagesRequestBuilderRequestsMetadata,
        navigationMetadata: StagesRequestBuilderNavigationMetadata,
    },
    stop: {
        requestsMetadata: StopRequestBuilderRequestsMetadata,
    },
    stopApplyDecisions: {
        requestsMetadata: StopApplyDecisionsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AccessReviewInstanceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: AccessReviewInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: AccessReviewInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAccessReviewInstanceFromDiscriminatorValue,
        queryParametersMapper: AccessReviewInstanceItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: AccessReviewInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAccessReviewInstanceFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAccessReviewInstance,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
