/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a resizeCloudPcPostRequestBody
 */
export function createResizeCloudPcPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResizeCloudPcPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoResizeCloudPcPostRequestBody(resizeCloudPcPostRequestBody: Partial<ResizeCloudPcPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { resizeCloudPcPostRequestBody.backingStoreEnabled = true; },
        "targetServicePlanId": n => { resizeCloudPcPostRequestBody.targetServicePlanId = n.getStringValue(); },
    }
}
export interface ResizeCloudPcPostRequestBody extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean;
    /**
     * The targetServicePlanId property
     */
    targetServicePlanId?: string;
}
/**
 * Provides operations to call the resizeCloudPc method.
 */
export interface ResizeCloudPcRequestBuilder extends BaseRequestBuilder<ResizeCloudPcRequestBuilder> {
    /**
     * Upgrade or downgrade an existing Cloud PC to another configuration with a new virtual CPU (vCPU) and storage size.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @deprecated The resizeCloudPc API is deprecated and will stop returning on Oct 30, 2023. Please use resize instead as of 2023-05/resizeCloudPc
     * @see {@link https://learn.microsoft.com/graph/api/manageddevice-resizecloudpc?view=graph-rest-1.0|Find more info here}
     */
     post(body: ResizeCloudPcPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Upgrade or downgrade an existing Cloud PC to another configuration with a new virtual CPU (vCPU) and storage size.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     * @deprecated The resizeCloudPc API is deprecated and will stop returning on Oct 30, 2023. Please use resize instead as of 2023-05/resizeCloudPc
     */
     toPostRequestInformation(body: ResizeCloudPcPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeResizeCloudPcPostRequestBody(writer: SerializationWriter, resizeCloudPcPostRequestBody: Partial<ResizeCloudPcPostRequestBody> | undefined = {}) : void {
    writer.writeStringValue("targetServicePlanId", resizeCloudPcPostRequestBody.targetServicePlanId);
    writer.writeAdditionalData(resizeCloudPcPostRequestBody.additionalData);
}
/**
 * Metadata for all the requests in the request builder.
 */
export const ResizeCloudPcRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContentAsync",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeResizeCloudPcPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const ResizeCloudPcRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/managedDevices/{managedDevice%2Did}/resizeCloudPc";
/* tslint:enable */
/* eslint-enable */
