/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRbacApplicationFromDiscriminatorValue, serializeRbacApplication, type RbacApplication } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { ResourceNamespacesRequestBuilderNavigationMetadata, ResourceNamespacesRequestBuilderRequestsMetadata, type ResourceNamespacesRequestBuilder } from './resourceNamespaces/index.js';
// @ts-ignore
import { RoleAssignmentApprovalsRequestBuilderNavigationMetadata, RoleAssignmentApprovalsRequestBuilderRequestsMetadata, type RoleAssignmentApprovalsRequestBuilder } from './roleAssignmentApprovals/index.js';
// @ts-ignore
import { RoleAssignmentsRequestBuilderNavigationMetadata, RoleAssignmentsRequestBuilderRequestsMetadata, type RoleAssignmentsRequestBuilder } from './roleAssignments/index.js';
// @ts-ignore
import { RoleAssignmentScheduleInstancesRequestBuilderNavigationMetadata, RoleAssignmentScheduleInstancesRequestBuilderRequestsMetadata, type RoleAssignmentScheduleInstancesRequestBuilder } from './roleAssignmentScheduleInstances/index.js';
// @ts-ignore
import { RoleAssignmentScheduleRequestsRequestBuilderNavigationMetadata, RoleAssignmentScheduleRequestsRequestBuilderRequestsMetadata, type RoleAssignmentScheduleRequestsRequestBuilder } from './roleAssignmentScheduleRequests/index.js';
// @ts-ignore
import { RoleAssignmentSchedulesRequestBuilderNavigationMetadata, RoleAssignmentSchedulesRequestBuilderRequestsMetadata, type RoleAssignmentSchedulesRequestBuilder } from './roleAssignmentSchedules/index.js';
// @ts-ignore
import { RoleDefinitionsRequestBuilderNavigationMetadata, RoleDefinitionsRequestBuilderRequestsMetadata, type RoleDefinitionsRequestBuilder } from './roleDefinitions/index.js';
// @ts-ignore
import { RoleEligibilityScheduleInstancesRequestBuilderNavigationMetadata, RoleEligibilityScheduleInstancesRequestBuilderRequestsMetadata, type RoleEligibilityScheduleInstancesRequestBuilder } from './roleEligibilityScheduleInstances/index.js';
// @ts-ignore
import { RoleEligibilityScheduleRequestsRequestBuilderNavigationMetadata, RoleEligibilityScheduleRequestsRequestBuilderRequestsMetadata, type RoleEligibilityScheduleRequestsRequestBuilder } from './roleEligibilityScheduleRequests/index.js';
// @ts-ignore
import { RoleEligibilitySchedulesRequestBuilderNavigationMetadata, RoleEligibilitySchedulesRequestBuilderRequestsMetadata, type RoleEligibilitySchedulesRequestBuilder } from './roleEligibilitySchedules/index.js';
// @ts-ignore
import { RoleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilderRequestsMetadata, type RoleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilder } from './roleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId/index.js';
// @ts-ignore
import { RoleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilderRequestsMetadata, type RoleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilder } from './roleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId/index.js';
// @ts-ignore
import { TransitiveRoleAssignmentsRequestBuilderNavigationMetadata, TransitiveRoleAssignmentsRequestBuilderRequestsMetadata, type TransitiveRoleAssignmentsRequestBuilder } from './transitiveRoleAssignments/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the entitlementManagement property of the microsoft.graph.roleManagement entity.
 */
export interface EntitlementManagementRequestBuilder extends BaseRequestBuilder<EntitlementManagementRequestBuilder> {
    /**
     * Provides operations to manage the resourceNamespaces property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get resourceNamespaces(): ResourceNamespacesRequestBuilder;
    /**
     * Provides operations to manage the roleAssignmentApprovals property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleAssignmentApprovals(): RoleAssignmentApprovalsRequestBuilder;
    /**
     * Provides operations to manage the roleAssignments property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleAssignments(): RoleAssignmentsRequestBuilder;
    /**
     * Provides operations to manage the roleAssignmentScheduleInstances property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleAssignmentScheduleInstances(): RoleAssignmentScheduleInstancesRequestBuilder;
    /**
     * Provides operations to manage the roleAssignmentScheduleRequests property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleAssignmentScheduleRequests(): RoleAssignmentScheduleRequestsRequestBuilder;
    /**
     * Provides operations to manage the roleAssignmentSchedules property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleAssignmentSchedules(): RoleAssignmentSchedulesRequestBuilder;
    /**
     * Provides operations to manage the roleDefinitions property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleDefinitions(): RoleDefinitionsRequestBuilder;
    /**
     * Provides operations to manage the roleEligibilityScheduleInstances property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleEligibilityScheduleInstances(): RoleEligibilityScheduleInstancesRequestBuilder;
    /**
     * Provides operations to manage the roleEligibilityScheduleRequests property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleEligibilityScheduleRequests(): RoleEligibilityScheduleRequestsRequestBuilder;
    /**
     * Provides operations to manage the roleEligibilitySchedules property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleEligibilitySchedules(): RoleEligibilitySchedulesRequestBuilder;
    /**
     * Provides operations to call the roleScheduleInstances method.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId(): RoleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilder;
    /**
     * Provides operations to call the roleSchedules method.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get roleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId(): RoleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilder;
    /**
     * Provides operations to manage the transitiveRoleAssignments property of the microsoft.graph.rbacApplication entity.
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
    get transitiveRoleAssignments(): TransitiveRoleAssignmentsRequestBuilder;
    /**
     * Delete navigation property entitlementManagement for roleManagement
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * The RbacApplication for Entitlement Management
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RbacApplication>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     get(requestConfiguration?: RequestConfiguration<EntitlementManagementRequestBuilderGetQueryParameters> | undefined) : Promise<RbacApplication | undefined>;
    /**
     * Update the navigation property entitlementManagement in roleManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RbacApplication>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     patch(body: RbacApplication, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RbacApplication | undefined>;
    /**
     * Delete navigation property entitlementManagement for roleManagement
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * The RbacApplication for Entitlement Management
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<EntitlementManagementRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property entitlementManagement in roleManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated This version is being deprecated and is scheduled for removal on 2025-12-01.Please migrate to the latest version before the removal date. as of 2025-01/PrivatePreview:microsoft.applicationAuthorization on 2025-01-01 and will be removed 2025-12-01
     */
     toPatchRequestInformation(body: RbacApplication, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The RbacApplication for Entitlement Management
 */
export interface EntitlementManagementRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const EntitlementManagementRequestBuilderUriTemplate = "{+baseurl}/roleManagement/entitlementManagement{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const EntitlementManagementRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EntitlementManagementRequestBuilderNavigationMetadata: Record<Exclude<keyof EntitlementManagementRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    resourceNamespaces: {
        requestsMetadata: ResourceNamespacesRequestBuilderRequestsMetadata,
        navigationMetadata: ResourceNamespacesRequestBuilderNavigationMetadata,
    },
    roleAssignmentApprovals: {
        requestsMetadata: RoleAssignmentApprovalsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleAssignmentApprovalsRequestBuilderNavigationMetadata,
    },
    roleAssignments: {
        requestsMetadata: RoleAssignmentsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleAssignmentsRequestBuilderNavigationMetadata,
    },
    roleAssignmentScheduleInstances: {
        requestsMetadata: RoleAssignmentScheduleInstancesRequestBuilderRequestsMetadata,
        navigationMetadata: RoleAssignmentScheduleInstancesRequestBuilderNavigationMetadata,
    },
    roleAssignmentScheduleRequests: {
        requestsMetadata: RoleAssignmentScheduleRequestsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleAssignmentScheduleRequestsRequestBuilderNavigationMetadata,
    },
    roleAssignmentSchedules: {
        requestsMetadata: RoleAssignmentSchedulesRequestBuilderRequestsMetadata,
        navigationMetadata: RoleAssignmentSchedulesRequestBuilderNavigationMetadata,
    },
    roleDefinitions: {
        requestsMetadata: RoleDefinitionsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleDefinitionsRequestBuilderNavigationMetadata,
    },
    roleEligibilityScheduleInstances: {
        requestsMetadata: RoleEligibilityScheduleInstancesRequestBuilderRequestsMetadata,
        navigationMetadata: RoleEligibilityScheduleInstancesRequestBuilderNavigationMetadata,
    },
    roleEligibilityScheduleRequests: {
        requestsMetadata: RoleEligibilityScheduleRequestsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleEligibilityScheduleRequestsRequestBuilderNavigationMetadata,
    },
    roleEligibilitySchedules: {
        requestsMetadata: RoleEligibilitySchedulesRequestBuilderRequestsMetadata,
        navigationMetadata: RoleEligibilitySchedulesRequestBuilderNavigationMetadata,
    },
    roleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId: {
        requestsMetadata: RoleScheduleInstancesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilderRequestsMetadata,
    },
    roleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionId: {
        requestsMetadata: RoleSchedulesdirectoryScopeIdDirectoryScopeIdAppScopeIdAppScopeIdPrincipalIdPrincipalIdRoleDefinitionIdRoleDefinitionIdRequestBuilderRequestsMetadata,
    },
    transitiveRoleAssignments: {
        requestsMetadata: TransitiveRoleAssignmentsRequestBuilderRequestsMetadata,
        navigationMetadata: TransitiveRoleAssignmentsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EntitlementManagementRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: EntitlementManagementRequestBuilderUriTemplate,
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: EntitlementManagementRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRbacApplicationFromDiscriminatorValue,
        queryParametersMapper: EntitlementManagementRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: EntitlementManagementRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRbacApplicationFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRbacApplication,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
