/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createLanguageProficiencyCollectionResponseFromDiscriminatorValue, createLanguageProficiencyFromDiscriminatorValue, serializeLanguageProficiency, type LanguageProficiency, type LanguageProficiencyCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/';
import { LanguageProficiencyItemRequestBuilderRequestsMetadata, type LanguageProficiencyItemRequestBuilder } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetOrderbyQueryParameterType = (typeof GetOrderbyQueryParameterTypeObject)[keyof typeof GetOrderbyQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Provides operations to manage the languages property of the microsoft.graph.profile entity.
 */
export interface LanguagesRequestBuilder extends BaseRequestBuilder<LanguagesRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the languages property of the microsoft.graph.profile entity.
     * @param languageProficiencyId The unique identifier of languageProficiency
     * @returns {LanguageProficiencyItemRequestBuilder}
     */
     byLanguageProficiencyId(languageProficiencyId: string) : LanguageProficiencyItemRequestBuilder;
    /**
     * Retrieve a list of languageProficiency objects from a user's profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LanguageProficiencyCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/profile-list-languages?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<LanguagesRequestBuilderGetQueryParameters> | undefined) : Promise<LanguageProficiencyCollectionResponse | undefined>;
    /**
     * Use this API to create a new languageProficiency object in a user's profile.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LanguageProficiency>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/profile-post-languages?view=graph-rest-1.0|Find more info here}
     */
     post(body: LanguageProficiency, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LanguageProficiency | undefined>;
    /**
     * Retrieve a list of languageProficiency objects from a user's profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LanguagesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Use this API to create a new languageProficiency object in a user's profile.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LanguageProficiency, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Retrieve a list of languageProficiency objects from a user's profile.
 */
export interface LanguagesRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: GetOrderbyQueryParameterType[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const LanguagesRequestBuilderUriTemplate = "{+baseurl}/users/{user%2Did}/profile/languages{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Provides operations to manage the languages property of the microsoft.graph.profile entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
} as const;
/**
 * Provides operations to manage the languages property of the microsoft.graph.profile entity.
 */
export const GetOrderbyQueryParameterTypeObject = {
    Id: "id",
    IdDesc: "id desc",
    AllowedAudiences: "allowedAudiences",
    AllowedAudiencesDesc: "allowedAudiences desc",
    CreatedBy: "createdBy",
    CreatedByDesc: "createdBy desc",
    CreatedDateTime: "createdDateTime",
    CreatedDateTimeDesc: "createdDateTime desc",
    Inference: "inference",
    InferenceDesc: "inference desc",
    IsSearchable: "isSearchable",
    IsSearchableDesc: "isSearchable desc",
    LastModifiedBy: "lastModifiedBy",
    LastModifiedByDesc: "lastModifiedBy desc",
    LastModifiedDateTime: "lastModifiedDateTime",
    LastModifiedDateTimeDesc: "lastModifiedDateTime desc",
    Source: "source",
    SourceDesc: "source desc",
    DisplayName: "displayName",
    DisplayNameDesc: "displayName desc",
    Proficiency: "proficiency",
    ProficiencyDesc: "proficiency desc",
    Reading: "reading",
    ReadingDesc: "reading desc",
    Spoken: "spoken",
    SpokenDesc: "spoken desc",
    Tag: "tag",
    TagDesc: "tag desc",
    ThumbnailUrl: "thumbnailUrl",
    ThumbnailUrlDesc: "thumbnailUrl desc",
    Written: "written",
    WrittenDesc: "written desc",
} as const;
/**
 * Provides operations to manage the languages property of the microsoft.graph.profile entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    AllowedAudiences: "allowedAudiences",
    CreatedBy: "createdBy",
    CreatedDateTime: "createdDateTime",
    Inference: "inference",
    IsSearchable: "isSearchable",
    LastModifiedBy: "lastModifiedBy",
    LastModifiedDateTime: "lastModifiedDateTime",
    Source: "source",
    DisplayName: "displayName",
    Proficiency: "proficiency",
    Reading: "reading",
    Spoken: "spoken",
    Tag: "tag",
    ThumbnailUrl: "thumbnailUrl",
    Written: "written",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const LanguagesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LanguagesRequestBuilderNavigationMetadata: Record<Exclude<keyof LanguagesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLanguageProficiencyId: {
        requestsMetadata: LanguageProficiencyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["languageProficiency%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LanguagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LanguagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLanguageProficiencyCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: LanguagesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: LanguagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLanguageProficiencyFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLanguageProficiency,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
