/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSharedEmailDomainInvitationCollectionResponseFromDiscriminatorValue, createSharedEmailDomainInvitationFromDiscriminatorValue, serializeSharedEmailDomainInvitation, type SharedEmailDomainInvitation, type SharedEmailDomainInvitationCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/index.js';
// @ts-ignore
import { SharedEmailDomainInvitationItemRequestBuilderRequestsMetadata, type SharedEmailDomainInvitationItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the sharedEmailDomainInvitations property of the microsoft.graph.domain entity.
 */
export interface SharedEmailDomainInvitationsRequestBuilder extends BaseRequestBuilder<SharedEmailDomainInvitationsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the sharedEmailDomainInvitations property of the microsoft.graph.domain entity.
     * @param sharedEmailDomainInvitationId The unique identifier of sharedEmailDomainInvitation
     * @returns {SharedEmailDomainInvitationItemRequestBuilder}
     */
     bySharedEmailDomainInvitationId(sharedEmailDomainInvitationId: string) : SharedEmailDomainInvitationItemRequestBuilder;
    /**
     * Get sharedEmailDomainInvitations from domains
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharedEmailDomainInvitationCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<SharedEmailDomainInvitationsRequestBuilderGetQueryParameters> | undefined) : Promise<SharedEmailDomainInvitationCollectionResponse | undefined>;
    /**
     * Create new navigation property to sharedEmailDomainInvitations for domains
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharedEmailDomainInvitation>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: SharedEmailDomainInvitation, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SharedEmailDomainInvitation | undefined>;
    /**
     * Get sharedEmailDomainInvitations from domains
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SharedEmailDomainInvitationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to sharedEmailDomainInvitations for domains
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SharedEmailDomainInvitation, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get sharedEmailDomainInvitations from domains
 */
export interface SharedEmailDomainInvitationsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const SharedEmailDomainInvitationsRequestBuilderUriTemplate = "{+baseurl}/domains/{domain%2Did}/sharedEmailDomainInvitations{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SharedEmailDomainInvitationsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SharedEmailDomainInvitationsRequestBuilderNavigationMetadata: Record<Exclude<keyof SharedEmailDomainInvitationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySharedEmailDomainInvitationId: {
        requestsMetadata: SharedEmailDomainInvitationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["sharedEmailDomainInvitation%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SharedEmailDomainInvitationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SharedEmailDomainInvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharedEmailDomainInvitationCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: SharedEmailDomainInvitationsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: SharedEmailDomainInvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharedEmailDomainInvitationFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSharedEmailDomainInvitation,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
