/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSharePointGroupIdentityMappingFromDiscriminatorValue, serializeSharePointGroupIdentityMapping, type SharePointGroupIdentityMapping } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the crossOrganizationGroupMappings property of the microsoft.graph.sharePointMigrationsRoot entity.
 */
export interface SharePointGroupIdentityMappingItemRequestBuilder extends BaseRequestBuilder<SharePointGroupIdentityMappingItemRequestBuilder> {
    /**
     * Delete navigation property crossOrganizationGroupMappings for solutions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Collection of group identity mappings for cross-organization migration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharePointGroupIdentityMapping>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<SharePointGroupIdentityMappingItemRequestBuilderGetQueryParameters> | undefined) : Promise<SharePointGroupIdentityMapping | undefined>;
    /**
     * Perform delta patch operations on group identity mappings for cross-organization migration. This operation supports bulk add, update, and delete actions for both Microsoft 365 groups and regular Microsoft Entra groups. Maximum of 50 items allowed in the value array.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharePointGroupIdentityMapping>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/sharepointgroupidentitymapping-update?view=graph-rest-beta|Find more info here}
     */
     patch(body: SharePointGroupIdentityMapping, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SharePointGroupIdentityMapping | undefined>;
    /**
     * Delete navigation property crossOrganizationGroupMappings for solutions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Collection of group identity mappings for cross-organization migration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SharePointGroupIdentityMappingItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Perform delta patch operations on group identity mappings for cross-organization migration. This operation supports bulk add, update, and delete actions for both Microsoft 365 groups and regular Microsoft Entra groups. Maximum of 50 items allowed in the value array.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: SharePointGroupIdentityMapping, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Collection of group identity mappings for cross-organization migration.
 */
export interface SharePointGroupIdentityMappingItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const SharePointGroupIdentityMappingItemRequestBuilderUriTemplate = "{+baseurl}/solutions/sharePoint/migrations/crossOrganizationGroupMappings/{sharePointGroupIdentityMapping%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SharePointGroupIdentityMappingItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SharePointGroupIdentityMappingItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SharePointGroupIdentityMappingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: SharePointGroupIdentityMappingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharePointGroupIdentityMappingFromDiscriminatorValue,
        queryParametersMapper: SharePointGroupIdentityMappingItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: SharePointGroupIdentityMappingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharePointGroupIdentityMappingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSharePointGroupIdentityMapping,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
