/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetMobileApplicationManagementAppConfigurationReportPostRequestBody}
 */
// @ts-ignore
export function createGetMobileApplicationManagementAppConfigurationReportPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetMobileApplicationManagementAppConfigurationReportPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetMobileApplicationManagementAppConfigurationReportPostRequestBody(getMobileApplicationManagementAppConfigurationReportPostRequestBody: Partial<GetMobileApplicationManagementAppConfigurationReportPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.backingStoreEnabled = true; },
        "filter": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.filter = n.getStringValue(); },
        "groupBy": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.groupBy = n.getCollectionOfPrimitiveValues<string>(); },
        "name": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.name = n.getStringValue(); },
        "orderBy": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.orderBy = n.getCollectionOfPrimitiveValues<string>(); },
        "search": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.search = n.getStringValue(); },
        "select": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.select = n.getCollectionOfPrimitiveValues<string>(); },
        "sessionId": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.sessionId = n.getStringValue(); },
        "skip": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.skip = n.getNumberValue(); },
        "top": n => { getMobileApplicationManagementAppConfigurationReportPostRequestBody.top = n.getNumberValue(); },
    }
}
export interface GetMobileApplicationManagementAppConfigurationReportPostRequestBody extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean | null;
    /**
     * The filter property
     */
    filter?: string | null;
    /**
     * The groupBy property
     */
    groupBy?: string[] | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The orderBy property
     */
    orderBy?: string[] | null;
    /**
     * The search property
     */
    search?: string | null;
    /**
     * The select property
     */
    select?: string[] | null;
    /**
     * The sessionId property
     */
    sessionId?: string | null;
    /**
     * The skip property
     */
    skip?: number | null;
    /**
     * The top property
     */
    top?: number | null;
}
/**
 * Provides operations to call the getMobileApplicationManagementAppConfigurationReport method.
 */
export interface GetMobileApplicationManagementAppConfigurationReportRequestBuilder extends BaseRequestBuilder<GetMobileApplicationManagementAppConfigurationReportRequestBuilder> {
    /**
     * Invoke action getMobileApplicationManagementAppConfigurationReport
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: GetMobileApplicationManagementAppConfigurationReportPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Invoke action getMobileApplicationManagementAppConfigurationReport
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: GetMobileApplicationManagementAppConfigurationReportPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetMobileApplicationManagementAppConfigurationReportPostRequestBody(writer: SerializationWriter, getMobileApplicationManagementAppConfigurationReportPostRequestBody: Partial<GetMobileApplicationManagementAppConfigurationReportPostRequestBody> | undefined | null = {}) : void {
    if (getMobileApplicationManagementAppConfigurationReportPostRequestBody) {
        writer.writeStringValue("filter", getMobileApplicationManagementAppConfigurationReportPostRequestBody.filter);
        writer.writeCollectionOfPrimitiveValues<string>("groupBy", getMobileApplicationManagementAppConfigurationReportPostRequestBody.groupBy);
        writer.writeStringValue("name", getMobileApplicationManagementAppConfigurationReportPostRequestBody.name);
        writer.writeCollectionOfPrimitiveValues<string>("orderBy", getMobileApplicationManagementAppConfigurationReportPostRequestBody.orderBy);
        writer.writeStringValue("search", getMobileApplicationManagementAppConfigurationReportPostRequestBody.search);
        writer.writeCollectionOfPrimitiveValues<string>("select", getMobileApplicationManagementAppConfigurationReportPostRequestBody.select);
        writer.writeStringValue("sessionId", getMobileApplicationManagementAppConfigurationReportPostRequestBody.sessionId);
        writer.writeNumberValue("skip", getMobileApplicationManagementAppConfigurationReportPostRequestBody.skip);
        writer.writeNumberValue("top", getMobileApplicationManagementAppConfigurationReportPostRequestBody.top);
        writer.writeAdditionalData(getMobileApplicationManagementAppConfigurationReportPostRequestBody.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const GetMobileApplicationManagementAppConfigurationReportRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/reports/getMobileApplicationManagementAppConfigurationReport";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetMobileApplicationManagementAppConfigurationReportRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetMobileApplicationManagementAppConfigurationReportRequestBuilderUriTemplate,
        responseBodyContentType: "application/octet-stream",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeGetMobileApplicationManagementAppConfigurationReportPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
