/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createManagementTemplateStepDeploymentCollectionResponseFromDiscriminatorValue, createManagementTemplateStepDeploymentFromDiscriminatorValue, serializeManagementTemplateStepDeployment, type ManagementTemplateStepDeployment, type ManagementTemplateStepDeploymentCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/managedTenants/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/';
import { ManagementTemplateStepDeploymentItemRequestBuilderNavigationMetadata, ManagementTemplateStepDeploymentItemRequestBuilderRequestsMetadata, type ManagementTemplateStepDeploymentItemRequestBuilder } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the deployments property of the microsoft.graph.managedTenants.managementTemplateStepVersion entity.
 */
export interface DeploymentsRequestBuilder extends BaseRequestBuilder<DeploymentsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the deployments property of the microsoft.graph.managedTenants.managementTemplateStepVersion entity.
     * @param managementTemplateStepDeploymentId The unique identifier of managementTemplateStepDeployment
     * @returns {ManagementTemplateStepDeploymentItemRequestBuilder}
     */
     byManagementTemplateStepDeploymentId(managementTemplateStepDeploymentId: string) : ManagementTemplateStepDeploymentItemRequestBuilder;
    /**
     * Get deployments from tenantRelationships
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ManagementTemplateStepDeploymentCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<DeploymentsRequestBuilderGetQueryParameters> | undefined) : Promise<ManagementTemplateStepDeploymentCollectionResponse | undefined>;
    /**
     * Create new navigation property to deployments for tenantRelationships
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ManagementTemplateStepDeployment>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: ManagementTemplateStepDeployment, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ManagementTemplateStepDeployment | undefined>;
    /**
     * Get deployments from tenantRelationships
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DeploymentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to deployments for tenantRelationships
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ManagementTemplateStepDeployment, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get deployments from tenantRelationships
 */
export interface DeploymentsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: GetOrderbyQueryParameterType[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetOrderbyQueryParameterType = (typeof GetOrderbyQueryParameterTypeObject)[keyof typeof GetOrderbyQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const DeploymentsRequestBuilderUriTemplate = "{+baseurl}/tenantRelationships/managedTenants/managementTemplateStepVersions/{managementTemplateStepVersion%2Did}/deployments{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const DeploymentsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DeploymentsRequestBuilderNavigationMetadata: Record<Exclude<keyof DeploymentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byManagementTemplateStepDeploymentId: {
        requestsMetadata: ManagementTemplateStepDeploymentItemRequestBuilderRequestsMetadata,
        navigationMetadata: ManagementTemplateStepDeploymentItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["managementTemplateStepDeployment%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DeploymentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DeploymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createManagementTemplateStepDeploymentCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: DeploymentsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: DeploymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createManagementTemplateStepDeploymentFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeManagementTemplateStepDeployment,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Provides operations to manage the deployments property of the microsoft.graph.managedTenants.managementTemplateStepVersion entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
    TemplateStepVersion: "templateStepVersion",
} as const;
/**
 * Provides operations to manage the deployments property of the microsoft.graph.managedTenants.managementTemplateStepVersion entity.
 */
export const GetOrderbyQueryParameterTypeObject = {
    Id: "id",
    IdDesc: "id desc",
    CreatedByUserId: "createdByUserId",
    CreatedByUserIdDesc: "createdByUserId desc",
    CreatedDateTime: "createdDateTime",
    CreatedDateTimeDesc: "createdDateTime desc",
    ErrorEscaped: "error",
    ErrorDesc: "error desc",
    LastActionByUserId: "lastActionByUserId",
    LastActionByUserIdDesc: "lastActionByUserId desc",
    LastActionDateTime: "lastActionDateTime",
    LastActionDateTimeDesc: "lastActionDateTime desc",
    Status: "status",
    StatusDesc: "status desc",
    TenantId: "tenantId",
    TenantIdDesc: "tenantId desc",
} as const;
/**
 * Provides operations to manage the deployments property of the microsoft.graph.managedTenants.managementTemplateStepVersion entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    CreatedByUserId: "createdByUserId",
    CreatedDateTime: "createdDateTime",
    ErrorEscaped: "error",
    LastActionByUserId: "lastActionByUserId",
    LastActionDateTime: "lastActionDateTime",
    Status: "status",
    TenantId: "tenantId",
    TemplateStepVersion: "templateStepVersion",
} as const;
/* tslint:enable */
/* eslint-enable */
