/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMailboxExclusionUnitCollectionResponseFromDiscriminatorValue, createMailboxExclusionUnitFromDiscriminatorValue, serializeMailboxExclusionUnit, type MailboxExclusionUnit, type MailboxExclusionUnitCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/index.js';
// @ts-ignore
import { MailboxExclusionUnitItemRequestBuilderRequestsMetadata, type MailboxExclusionUnitItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the mailboxExclusionUnits property of the microsoft.graph.backupRestoreRoot entity.
 */
export interface MailboxExclusionUnitsRequestBuilder extends BaseRequestBuilder<MailboxExclusionUnitsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the mailboxExclusionUnits property of the microsoft.graph.backupRestoreRoot entity.
     * @param mailboxExclusionUnitId The unique identifier of mailboxExclusionUnit
     * @returns {MailboxExclusionUnitItemRequestBuilder}
     */
     byMailboxExclusionUnitId(mailboxExclusionUnitId: string) : MailboxExclusionUnitItemRequestBuilder;
    /**
     * The list of mailbox exclusion units in the tenant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MailboxExclusionUnitCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<MailboxExclusionUnitsRequestBuilderGetQueryParameters> | undefined) : Promise<MailboxExclusionUnitCollectionResponse | undefined>;
    /**
     * Create new navigation property to mailboxExclusionUnits for solutions
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MailboxExclusionUnit>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: MailboxExclusionUnit, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MailboxExclusionUnit | undefined>;
    /**
     * The list of mailbox exclusion units in the tenant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MailboxExclusionUnitsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to mailboxExclusionUnits for solutions
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MailboxExclusionUnit, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The list of mailbox exclusion units in the tenant.
 */
export interface MailboxExclusionUnitsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const MailboxExclusionUnitsRequestBuilderUriTemplate = "{+baseurl}/solutions/backupRestore/mailboxExclusionUnits{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const MailboxExclusionUnitsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MailboxExclusionUnitsRequestBuilderNavigationMetadata: Record<Exclude<keyof MailboxExclusionUnitsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byMailboxExclusionUnitId: {
        requestsMetadata: MailboxExclusionUnitItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["mailboxExclusionUnit%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MailboxExclusionUnitsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MailboxExclusionUnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMailboxExclusionUnitCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: MailboxExclusionUnitsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: MailboxExclusionUnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMailboxExclusionUnitFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMailboxExclusionUnit,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
