/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeviceManagementResourceAccessProfileBaseFromDiscriminatorValue, deserializeIntoBaseCollectionPaginationCountResponse, PolicyPlatformType, PolicyPlatformTypeObject, serializeBaseCollectionPaginationCountResponse, serializeDeviceManagementResourceAccessProfileBase, type BaseCollectionPaginationCountResponse, type DeviceManagementResourceAccessProfileBase } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryByPlatformTypePostRequestBody}
 */
export function createQueryByPlatformTypePostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryByPlatformTypePostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryByPlatformTypePostResponse}
 */
export function createQueryByPlatformTypePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryByPlatformTypePostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoQueryByPlatformTypePostRequestBody(queryByPlatformTypePostRequestBody: Partial<QueryByPlatformTypePostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { queryByPlatformTypePostRequestBody.backingStoreEnabled = true; },
        "platformType": n => { queryByPlatformTypePostRequestBody.platformType = n.getEnumValue<PolicyPlatformType>(PolicyPlatformTypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoQueryByPlatformTypePostResponse(queryByPlatformTypePostResponse: Partial<QueryByPlatformTypePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(queryByPlatformTypePostResponse),
        "value": n => { queryByPlatformTypePostResponse.value = n.getCollectionOfObjectValues<DeviceManagementResourceAccessProfileBase>(createDeviceManagementResourceAccessProfileBaseFromDiscriminatorValue); },
    }
}
export interface QueryByPlatformTypePostRequestBody extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean;
    /**
     * Supported platform types for policies.
     */
    platformType?: PolicyPlatformType;
}
export interface QueryByPlatformTypePostResponse extends BaseCollectionPaginationCountResponse, Parsable {
    /**
     * The value property
     */
    value?: DeviceManagementResourceAccessProfileBase[];
}
/**
 * Provides operations to call the queryByPlatformType method.
 */
export interface QueryByPlatformTypeRequestBuilder extends BaseRequestBuilder<QueryByPlatformTypeRequestBuilder> {
    /**
     * Invoke action queryByPlatformType
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryByPlatformTypePostResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: QueryByPlatformTypePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryByPlatformTypePostResponse | undefined>;
    /**
     * Invoke action queryByPlatformType
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryByPlatformTypePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeQueryByPlatformTypePostRequestBody(writer: SerializationWriter, queryByPlatformTypePostRequestBody: Partial<QueryByPlatformTypePostRequestBody> | undefined = {}) : void {
    writer.writeEnumValue<PolicyPlatformType>("platformType", queryByPlatformTypePostRequestBody.platformType);
    writer.writeAdditionalData(queryByPlatformTypePostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeQueryByPlatformTypePostResponse(writer: SerializationWriter, queryByPlatformTypePostResponse: Partial<QueryByPlatformTypePostResponse> | undefined = {}) : void {
    serializeBaseCollectionPaginationCountResponse(writer, queryByPlatformTypePostResponse)
    writer.writeCollectionOfObjectValues<DeviceManagementResourceAccessProfileBase>("value", queryByPlatformTypePostResponse.value, serializeDeviceManagementResourceAccessProfileBase);
}
/**
 * Uri template for the request builder.
 */
export const QueryByPlatformTypeRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/resourceAccessProfiles/queryByPlatformType";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryByPlatformTypeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryByPlatformTypeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createQueryByPlatformTypePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryByPlatformTypePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
