/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGroupAnalyticsCollectionResponseFromDiscriminatorValue, createGroupAnalyticsFromDiscriminatorValue, serializeGroupAnalytics, type GroupAnalytics, type GroupAnalyticsCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/index.js';
// @ts-ignore
import { GroupAnalyticsItemRequestBuilderRequestsMetadata, type GroupAnalyticsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the groups property of the microsoft.graph.identityAnalyticsRoot entity.
 */
export interface GroupsRequestBuilder extends BaseRequestBuilder<GroupsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the groups property of the microsoft.graph.identityAnalyticsRoot entity.
     * @param groupAnalyticsId The unique identifier of groupAnalytics
     * @returns {GroupAnalyticsItemRequestBuilder}
     */
     byGroupAnalyticsId(groupAnalyticsId: string) : GroupAnalyticsItemRequestBuilder;
    /**
     * Get a list of the groupAnalytics objects and their properties for a Microsoft Entra tenant. Each object holds point-in-time identity analytics for one group.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GroupAnalyticsCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/identityanalyticsroot-list-groups?view=graph-rest-beta|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<GroupsRequestBuilderGetQueryParameters> | undefined) : Promise<GroupAnalyticsCollectionResponse | undefined>;
    /**
     * Create new navigation property to groups for reports
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GroupAnalytics>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: GroupAnalytics, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GroupAnalytics | undefined>;
    /**
     * Get a list of the groupAnalytics objects and their properties for a Microsoft Entra tenant. Each object holds point-in-time identity analytics for one group.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GroupsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to groups for reports
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: GroupAnalytics, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of the groupAnalytics objects and their properties for a Microsoft Entra tenant. Each object holds point-in-time identity analytics for one group.
 */
export interface GroupsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const GroupsRequestBuilderUriTemplate = "{+baseurl}/reports/identityAnalytics/groups{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const GroupsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GroupsRequestBuilderNavigationMetadata: Record<Exclude<keyof GroupsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGroupAnalyticsId: {
        requestsMetadata: GroupAnalyticsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["groupAnalytics%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const GroupsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GroupsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGroupAnalyticsCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: GroupsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: GroupsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGroupAnalyticsFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeGroupAnalytics,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
