/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUserExperienceAnalyticsResourcePerformanceCollectionResponseFromDiscriminatorValue, createUserExperienceAnalyticsResourcePerformanceFromDiscriminatorValue, serializeUserExperienceAnalyticsResourcePerformance, type UserExperienceAnalyticsResourcePerformance, type UserExperienceAnalyticsResourcePerformanceCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/';
import { type UserExperienceAnalyticsResourcePerformanceItemRequestBuilder, UserExperienceAnalyticsResourcePerformanceItemRequestBuilderRequestsMetadata } from './item/';
import { SummarizeDeviceResourcePerformanceWithSummarizeByRequestBuilderRequestsMetadata, type SummarizeDeviceResourcePerformanceWithSummarizeByRequestBuilder } from './summarizeDeviceResourcePerformanceWithSummarizeBy/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the userExperienceAnalyticsResourcePerformance property of the microsoft.graph.deviceManagement entity.
 */
export interface UserExperienceAnalyticsResourcePerformanceRequestBuilder extends BaseRequestBuilder<UserExperienceAnalyticsResourcePerformanceRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the userExperienceAnalyticsResourcePerformance property of the microsoft.graph.deviceManagement entity.
     * @param userExperienceAnalyticsResourcePerformanceId The unique identifier of userExperienceAnalyticsResourcePerformance
     * @returns {UserExperienceAnalyticsResourcePerformanceItemRequestBuilder}
     */
     byUserExperienceAnalyticsResourcePerformanceId(userExperienceAnalyticsResourcePerformanceId: string) : UserExperienceAnalyticsResourcePerformanceItemRequestBuilder;
    /**
     * User experience analytics resource performance
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserExperienceAnalyticsResourcePerformanceCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<UserExperienceAnalyticsResourcePerformanceRequestBuilderGetQueryParameters> | undefined) : Promise<UserExperienceAnalyticsResourcePerformanceCollectionResponse | undefined>;
    /**
     * Create new navigation property to userExperienceAnalyticsResourcePerformance for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserExperienceAnalyticsResourcePerformance>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: UserExperienceAnalyticsResourcePerformance, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserExperienceAnalyticsResourcePerformance | undefined>;
    /**
     * Provides operations to call the summarizeDeviceResourcePerformance method.
     * @param summarizeBy Usage: summarizeBy='{summarizeBy}'
     * @returns {SummarizeDeviceResourcePerformanceWithSummarizeByRequestBuilder}
     */
     summarizeDeviceResourcePerformanceWithSummarizeBy(summarizeBy: string | undefined) : SummarizeDeviceResourcePerformanceWithSummarizeByRequestBuilder;
    /**
     * User experience analytics resource performance
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<UserExperienceAnalyticsResourcePerformanceRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to userExperienceAnalyticsResourcePerformance for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: UserExperienceAnalyticsResourcePerformance, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * User experience analytics resource performance
 */
export interface UserExperienceAnalyticsResourcePerformanceRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const UserExperienceAnalyticsResourcePerformanceRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/userExperienceAnalyticsResourcePerformance{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const UserExperienceAnalyticsResourcePerformanceRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UserExperienceAnalyticsResourcePerformanceRequestBuilderNavigationMetadata: Record<Exclude<keyof UserExperienceAnalyticsResourcePerformanceRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserExperienceAnalyticsResourcePerformanceId: {
        requestsMetadata: UserExperienceAnalyticsResourcePerformanceItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userExperienceAnalyticsResourcePerformance%2Did"],
    },
    summarizeDeviceResourcePerformanceWithSummarizeBy: {
        requestsMetadata: SummarizeDeviceResourcePerformanceWithSummarizeByRequestBuilderRequestsMetadata,
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UserExperienceAnalyticsResourcePerformanceRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UserExperienceAnalyticsResourcePerformanceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserExperienceAnalyticsResourcePerformanceCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: UserExperienceAnalyticsResourcePerformanceRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: UserExperienceAnalyticsResourcePerformanceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserExperienceAnalyticsResourcePerformanceFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUserExperienceAnalyticsResourcePerformance,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
