/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWindowsDriverUpdateProfileCollectionResponseFromDiscriminatorValue, createWindowsDriverUpdateProfileFromDiscriminatorValue, serializeWindowsDriverUpdateProfile, type WindowsDriverUpdateProfile, type WindowsDriverUpdateProfileCollectionResponse } from '@microsoft/msgraph-beta-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/index.js';
// @ts-ignore
import { type WindowsDriverUpdateProfileItemRequestBuilder, WindowsDriverUpdateProfileItemRequestBuilderNavigationMetadata, WindowsDriverUpdateProfileItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the windowsDriverUpdateProfiles property of the microsoft.graph.deviceManagement entity.
 */
export interface WindowsDriverUpdateProfilesRequestBuilder extends BaseRequestBuilder<WindowsDriverUpdateProfilesRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the windowsDriverUpdateProfiles property of the microsoft.graph.deviceManagement entity.
     * @param windowsDriverUpdateProfileId The unique identifier of windowsDriverUpdateProfile
     * @returns {WindowsDriverUpdateProfileItemRequestBuilder}
     */
     byWindowsDriverUpdateProfileId(windowsDriverUpdateProfileId: string) : WindowsDriverUpdateProfileItemRequestBuilder;
    /**
     * A collection of windows driver update profiles
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WindowsDriverUpdateProfileCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<WindowsDriverUpdateProfilesRequestBuilderGetQueryParameters> | undefined) : Promise<WindowsDriverUpdateProfileCollectionResponse | undefined>;
    /**
     * Create new navigation property to windowsDriverUpdateProfiles for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WindowsDriverUpdateProfile>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: WindowsDriverUpdateProfile, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WindowsDriverUpdateProfile | undefined>;
    /**
     * A collection of windows driver update profiles
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WindowsDriverUpdateProfilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to windowsDriverUpdateProfiles for deviceManagement
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WindowsDriverUpdateProfile, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * A collection of windows driver update profiles
 */
export interface WindowsDriverUpdateProfilesRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const WindowsDriverUpdateProfilesRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/windowsDriverUpdateProfiles{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const WindowsDriverUpdateProfilesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WindowsDriverUpdateProfilesRequestBuilderNavigationMetadata: Record<Exclude<keyof WindowsDriverUpdateProfilesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWindowsDriverUpdateProfileId: {
        requestsMetadata: WindowsDriverUpdateProfileItemRequestBuilderRequestsMetadata,
        navigationMetadata: WindowsDriverUpdateProfileItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["windowsDriverUpdateProfile%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WindowsDriverUpdateProfilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WindowsDriverUpdateProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWindowsDriverUpdateProfileCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: WindowsDriverUpdateProfilesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: WindowsDriverUpdateProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWindowsDriverUpdateProfileFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWindowsDriverUpdateProfile,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
