/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { RefRequestBuilderRequestsMetadata, RefRequestBuilderUriTemplate, type RefRequestBuilder } from './ref/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /identity/b2cUserFlows/{b2cIdentityUserFlow-id}/identityProviders/{identityProvider-id}
 */
export interface IdentityProviderItemRequestBuilder extends BaseRequestBuilder<IdentityProviderItemRequestBuilder> {
    /**
     * Provides operations to manage the collection of identityContainer entities.
     */
    get ref(): RefRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IdentityProviderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof IdentityProviderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    ref: {
        uriTemplate: RefRequestBuilderUriTemplate,
        requestsMetadata: RefRequestBuilderRequestsMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const IdentityProviderItemRequestBuilderUriTemplate = "{+baseurl}/identity/b2cUserFlows/{b2cIdentityUserFlow%2Did}/identityProviders/{identityProvider%2Did}";
/* tslint:enable */
/* eslint-enable */
