/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCertificateBasedApplicationConfigurationFromDiscriminatorValue, serializeCertificateBasedApplicationConfiguration, type CertificateBasedApplicationConfiguration } from '@microsoft/msgraph-beta-sdk/models/';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-beta-sdk/models/oDataErrors/';
// @ts-ignore
import { TrustedCertificateAuthoritiesRequestBuilderNavigationMetadata, TrustedCertificateAuthoritiesRequestBuilderRequestsMetadata, type TrustedCertificateAuthoritiesRequestBuilder } from './trustedCertificateAuthorities/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the certificateBasedApplicationConfigurations property of the microsoft.graph.certificateAuthorityPath entity.
 */
export interface CertificateBasedApplicationConfigurationItemRequestBuilder extends BaseRequestBuilder<CertificateBasedApplicationConfigurationItemRequestBuilder> {
    /**
     * Provides operations to manage the trustedCertificateAuthorities property of the microsoft.graph.trustedCertificateAuthorityAsEntityBase entity.
     */
    get trustedCertificateAuthorities(): TrustedCertificateAuthoritiesRequestBuilder;
    /**
     * Delete navigation property certificateBasedApplicationConfigurations for directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Defines the trusted certificate authorities for certificates that can be added to apps and service principals in the tenant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CertificateBasedApplicationConfiguration>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<CertificateBasedApplicationConfigurationItemRequestBuilderGetQueryParameters> | undefined) : Promise<CertificateBasedApplicationConfiguration | undefined>;
    /**
     * Update the navigation property certificateBasedApplicationConfigurations in directory
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CertificateBasedApplicationConfiguration>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: CertificateBasedApplicationConfiguration, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CertificateBasedApplicationConfiguration | undefined>;
    /**
     * Delete navigation property certificateBasedApplicationConfigurations for directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Defines the trusted certificate authorities for certificates that can be added to apps and service principals in the tenant.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CertificateBasedApplicationConfigurationItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property certificateBasedApplicationConfigurations in directory
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: CertificateBasedApplicationConfiguration, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Defines the trusted certificate authorities for certificates that can be added to apps and service principals in the tenant.
 */
export interface CertificateBasedApplicationConfigurationItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const CertificateBasedApplicationConfigurationItemRequestBuilderUriTemplate = "{+baseurl}/directory/certificateAuthorities/certificateBasedApplicationConfigurations/{certificateBasedApplicationConfiguration%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CertificateBasedApplicationConfigurationItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CertificateBasedApplicationConfigurationItemRequestBuilderNavigationMetadata: Record<Exclude<keyof CertificateBasedApplicationConfigurationItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    trustedCertificateAuthorities: {
        requestsMetadata: TrustedCertificateAuthoritiesRequestBuilderRequestsMetadata,
        navigationMetadata: TrustedCertificateAuthoritiesRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CertificateBasedApplicationConfigurationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: CertificateBasedApplicationConfigurationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: CertificateBasedApplicationConfigurationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCertificateBasedApplicationConfigurationFromDiscriminatorValue,
        queryParametersMapper: CertificateBasedApplicationConfigurationItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: CertificateBasedApplicationConfigurationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCertificateBasedApplicationConfigurationFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCertificateBasedApplicationConfiguration,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
